name: Deploy StreamVerse to Azure

# This workflow runs automatically on pushes to the 'main' branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1. Checks out your repository's code
      - uses: actions/checkout@v3
        with:
          submodules: true

      # 2. Deploys the code to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # This is a secret key that Azure will create for you
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          
          # --- Project Configuration ---
          # Your index.html is in the main folder
          app_location: "/"  
          # You don't have a separate API folder
          api_location: ""   
          # Your project doesn't need a build step
          output_location: ""
